arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.2
  kinematics_solver_attempts: 3
  root: arm_link_sh0
  tip:  arm_link_fngr
